@extends('layouts.master-pegawai')
@section('content-pegawai')

<div class="card">
    <div class="card-header">
        Laporan
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-sm-5">
                <div class="form-group">
                    <label>Periode : </label>
                    <select name="periode" id="periode" class="form-control">
                        <option value="">Pilih periode</option>
                        <option value="">Bulanan</option>
                        <option value="">Harian</option>
                    </select>
                </div>
            </div>

        </div>

        <div class="row">
        <div class="col-sm-4">
                <div class="form-group">
                    <label for="">Dari tanggal : </label><input type="date" class="form-control" name="tgl_awal" id="tgl-awal">
                </div>
            </div>

            <div class="col-sm-4">
                <div class="form-group">
                    <label for="">Hingga tanggal : </label><input type="date" class="form-control" name="tgl_akhir" id="tgl-akhir">
                </div>
            </div>
        </div>

        <div class="row">
        <div class="col-sm-4">
                <div class="form-group">
                    <label for="">Pilih Bulan : </label>
                    <input type="month" class="form-control" name="" id="bulan">
                </div>
            </div>
        </div>
        <button class="btn btn-primary mb-2" id="filter">Cari</button>
        <div class="row">
            <div class="col-lg-12">
            <div class="table-responsive mr-0">
                    <table class="table table-striped dataTable no-footer" id="table-laporan">
                        <thead>
                            <tr role="row">
                                <th>Id Pesanan</th>
                                <th>Nama Pelanggan</th>
                                <th>Tanggal Pemesanan</th>
                                <th>Total Harga</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection
@push('script')
<script>
    $(document).ready(function(){
        let periode = new Date().toLocaleDateString('en-CA');
        console.log(periode);

        let tblLaporan = $('#table-laporan').DataTable({
            "processing": true,
            "serverSide": true,
            ajax:{
                    url:"{{ route('kasir.laporan') }}",
                    data: function (d) {
                        d.bulan = $('#bulan').val();
                    }
                },
            columns: [
                {data: 'id_pesanan', name: 'id'},
                {data: 'nama_pelanggan', name: 'name'},
                {data: 'tanggal_pemesanan', name: 'email'},
                {data: 'total_pembayaran', name: 'total harga'},
                {data: 'action', name: 'action'},
            ],
            dom: 'Bfrtip',
            buttons: [
                'print',
                {
                    messageTop : 'Laporan Periode : '+periode,
                    messageBottom : 'tes',
                    text: 'Download',
                    extend: 'pdfHtml5',
                    title:'Laporan',
                    customize: function ( doc ) {
                        // Splice the image in after the header, but before the table
                        // doc.content.splice( 1, 0, {
                        //     margin: [ 0, 0, 0, 12 ],
                        // } );
                        // Data URL generated by http://dataurl.net/#dataurlmaker
                        doc.content[2].table.widths = [
                            '*','auto'
                        ];
                        console.log(doc);
                    }
                }
                
            ]
        } );

        $('#filter').click(function(){
            tblLaporan.draw();
            
        })
    })
</script>
@endpush